[project]
name = "agent-self-reflection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.23.0",
    "openai>=1.93.0",
    "pytest>=8.4.1",
    "requests>=2.32.4",
]
